# Generated by Django 5.1.3 on 2024-11-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_alter_accountsettings_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsettings',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='accountsettings',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
