# Generated by Django 5.1.3 on 2024-11-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0004_alter_accountsettings_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('on-demand', 'On-demand')], max_length=50),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=50),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], max_length=50),
        ),
    ]
